//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Course {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Course() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Course", typeof(Course).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرفقات.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الساعات الدورة.
        /// </summary>
        public static string CourseDays {
            get {
                return ResourceManager.GetString("CourseDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم  المشاركة.
        /// </summary>
        public static string CourseName {
            get {
                return ResourceManager.GetString("CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكان المشاركة.
        /// </summary>
        public static string CoursePlace {
            get {
                return ResourceManager.GetString("CoursePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المشاركة.
        /// </summary>
        public static string CourseTypes {
            get {
                return ResourceManager.GetString("CourseTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الدورة.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقدير.
        /// </summary>
        public static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النسبة المئوية.
        /// </summary>
        public static string DegreePercentage {
            get {
                return ResourceManager.GetString("DegreePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الطالب.
        /// </summary>
        public static string EmployeeID {
            get {
                return ResourceManager.GetString("EmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد ساعات الدورة مطلوب.
        /// </summary>
        public static string RequiredCourseDays {
            get {
                return ResourceManager.GetString("RequiredCourseDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الدورة مطلوب.
        /// </summary>
        public static string RequiredCourseName {
            get {
                return ResourceManager.GetString("RequiredCourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكان الدورة مطلوب.
        /// </summary>
        public static string RequiredCoursePlace {
            get {
                return ResourceManager.GetString("RequiredCoursePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المشاركة مطلوب.
        /// </summary>
        public static string RequiredCourseTypes {
            get {
                return ResourceManager.GetString("RequiredCourseTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الدورة مطلوب.
        /// </summary>
        public static string RequiredDate {
            get {
                return ResourceManager.GetString("RequiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقدير مطلوب.
        /// </summary>
        public static string RequiredDegree {
            get {
                return ResourceManager.GetString("RequiredDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النسبة المئوية مطلوب.
        /// </summary>
        public static string RequiredDegreePercentage {
            get {
                return ResourceManager.GetString("RequiredDegreePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال عدد ساعات الدورة رقم صحيح.
        /// </summary>
        public static string ValidateCourseDays {
            get {
                return ResourceManager.GetString("ValidateCourseDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال النسبة المئوية رقم صحيح من 0 الي 100.
        /// </summary>
        public static string ValidateDegreePercentage {
            get {
                return ResourceManager.GetString("ValidateDegreePercentage", resourceCulture);
            }
        }
    }
}
