//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicCommitteeUsers
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int FacultyID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> DegreeID { get; set; }
    
        public virtual DashBoard_Users DashBoard_Users { get; set; }
    }
}
