//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountSecurity
    {
        public int ID { get; set; }
        public int AccountId { get; set; }
        public int UserId { get; set; }
    
        public virtual COA COA { get; set; }
        public virtual Users Users { get; set; }
    }
}
