//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityRequestDetails
    {
        public int ID { get; set; }
        public int ActivityRequestMaster_ID { get; set; }
        public int Degree_ID { get; set; }
        public int User_ID { get; set; }
        public System.DateTime InsertionDate { get; set; }
        public int Student_ID { get; set; }
    
        public virtual ActivityConfig ActivityConfig { get; set; }
        public virtual ActivityRequestMaster ActivityRequestMaster { get; set; }
        public virtual DashBoard_Users DashBoard_Users { get; set; }
    }
}
