//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityRequestsArchiveAttachments
    {
        public int Id { get; set; }
        public int ActivityRequests_Id { get; set; }
        public string FileName { get; set; }
        public string Path { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual ActivityRequestsArchive ActivityRequestsArchive { get; set; }
    }
}
