//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityRequestMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivityRequestMaster()
        {
            this.ActivityRequestDetails = new HashSet<ActivityRequestDetails>();
            this.ActivityRequestMasterAttachments = new HashSet<ActivityRequestMasterAttachments>();
        }
    
        public int ID { get; set; }
        public int Activity_ID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int Location_ID { get; set; }
        public int Type_ID { get; set; }
        public int HoursNo { get; set; }
        public int YearName { get; set; }
        public string ActivityNo { get; set; }
        public Nullable<bool> ApprovedStatus { get; set; }
        public string StatusNotes { get; set; }
        public Nullable<int> ApprovedByUserID { get; set; }
        public int User_ID { get; set; }
        public System.DateTime InsertionDate { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public Nullable<bool> IsReturned { get; set; }
    
        public virtual ActivityConfig ActivityConfig { get; set; }
        public virtual ActivityConfig ActivityConfig1 { get; set; }
        public virtual ActivityConfig ActivityConfig2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityRequestDetails> ActivityRequestDetails { get; set; }
        public virtual ActivityRequestMaster ActivityRequestMaster1 { get; set; }
        public virtual ActivityRequestMaster ActivityRequestMaster2 { get; set; }
        public virtual ActivityRequestMaster ActivityRequestMaster11 { get; set; }
        public virtual ActivityRequestMaster ActivityRequestMaster3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityRequestMasterAttachments> ActivityRequestMasterAttachments { get; set; }
        public virtual DashBoard_Users DashBoard_Users { get; set; }
        public virtual DashBoard_Users DashBoard_Users1 { get; set; }
    }
}
