//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityRequestsArchive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivityRequestsArchive()
        {
            this.ActivityApprovedPhases = new HashSet<ActivityApprovedPhases>();
            this.ActivityRequestsArchiveAttachments = new HashSet<ActivityRequestsArchiveAttachments>();
        }
    
        public int ID { get; set; }
        public int Student_ID { get; set; }
        public string Name { get; set; }
        public string Duration { get; set; }
        public string Location { get; set; }
        public string Type { get; set; }
        public string Degree { get; set; }
        public decimal Ratio { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime InsertionDate { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> RefusedbyID { get; set; }
        public string RefuseReson { get; set; }
        public Nullable<int> ApprovedbyID { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityApprovedPhases> ActivityApprovedPhases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityRequestsArchiveAttachments> ActivityRequestsArchiveAttachments { get; set; }
        public virtual DashBoard_Users DashBoard_Users { get; set; }
    }
}
