//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivityConfig()
        {
            this.ActivityRequestDetails = new HashSet<ActivityRequestDetails>();
            this.ActivityRequestMaster = new HashSet<ActivityRequestMaster>();
            this.ActivityRequestMaster1 = new HashSet<ActivityRequestMaster>();
            this.ActivityRequestMaster2 = new HashSet<ActivityRequestMaster>();
        }
    
        public int ID { get; set; }
        public string Key { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public int User_ID { get; set; }
        public System.DateTime InsertionDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityRequestDetails> ActivityRequestDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityRequestMaster> ActivityRequestMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityRequestMaster> ActivityRequestMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityRequestMaster> ActivityRequestMaster2 { get; set; }
        public virtual DashBoard_Users DashBoard_Users { get; set; }
    }
}
