//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvanceReceiveMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdvanceReceiveMaster()
        {
            this.AdvanceReceiveDetails = new HashSet<AdvanceReceiveDetails>();
        }
    
        public int ID { get; set; }
        public System.DateTime InsertionDate { get; set; }
        public int COA_ID { get; set; }
        public Nullable<int> GJH_ID { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public int User_Id { get; set; }
        public int Student_Id { get; set; }
        public string DocNumber { get; set; }
        public string DocHeader { get; set; }
        public string DocNotes { get; set; }
        public decimal TotalValue { get; set; }
        public Nullable<int> PayrollId { get; set; }
        public Nullable<bool> IsPrinted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvanceReceiveDetails> AdvanceReceiveDetails { get; set; }
        public virtual Payroll Payroll { get; set; }
        public virtual DashBoard_Users DashBoard_Users { get; set; }
    }
}
