//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvanceReceiveDetails
    {
        public int ID { get; set; }
        public decimal NetValue { get; set; }
        public int AdvancePaymentDetails_Id { get; set; }
        public int AdvanceReceiveMaster_Id { get; set; }
    
        public virtual AdvancePaymentDetails AdvancePaymentDetails { get; set; }
        public virtual AdvanceReceiveMaster AdvanceReceiveMaster { get; set; }
    }
}
