//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvanceSettingConfig
    {
        public int ID { get; set; }
        public string Key { get; set; }
        public string KeyAr { get; set; }
        public string Value { get; set; }
        public string Type { get; set; }
        public bool IsVisible { get; set; }
    }
}
