//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvanceRequestsAttachment
    {
        public int Id { get; set; }
        public int AdvanceRequests_Id { get; set; }
        public string FileName { get; set; }
        public string Path { get; set; }
        public int UserId { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual AdvanceRequests AdvanceRequests { get; set; }
    }
}
