//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvanceRequestDetails
    {
        public int AdvanceRequestDetailsId { get; set; }
        public int AdvanceRequestId { get; set; }
        public int MonthId { get; set; }
        public double MonthlyValue { get; set; }
        public Nullable<int> AdvanceId { get; set; }
    }
}
