//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvanceRequest
    {
        public int ID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<decimal> AdvanceValue { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string MonthsNumbers { get; set; }
        public Nullable<decimal> MonthlyPremium { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> RefusedBy { get; set; }
        public string AdvanceName { get; set; }
        public Nullable<int> FirstApprove { get; set; }
        public Nullable<int> ScondApprove { get; set; }
        public string RequestType { get; set; }
        public Nullable<int> AdvanceSettingId { get; set; }
        public string Attachments { get; set; }
        public Nullable<int> PaidBy { get; set; }
        public string RefuseReason { get; set; }
    }
}
