//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvancePaymentDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdvancePaymentDetails()
        {
            this.AdvanceReceiveDetails = new HashSet<AdvanceReceiveDetails>();
        }
    
        public int ID { get; set; }
        public decimal NetValue { get; set; }
        public int AdvanceRequests_Id { get; set; }
        public int AdvancePaymentMaster_Id { get; set; }
    
        public virtual AdvancePaymentMaster AdvancePaymentMaster { get; set; }
        public virtual AdvanceRequests AdvanceRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvanceReceiveDetails> AdvanceReceiveDetails { get; set; }
    }
}
