//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvanceSettings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdvanceSettings()
        {
            this.AdvanceRequests = new HashSet<AdvanceRequests>();
        }
    
        public int AdvanceSettingId { get; set; }
        public string AdvanceSettingName { get; set; }
        public string AdvanceType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> COAID { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string ValueType { get; set; }
        public Nullable<decimal> MaxRequestValue { get; set; }
        public Nullable<int> CoaId_RecieveFromPayroll { get; set; }
        public Nullable<bool> IsConditional { get; set; }
        public Nullable<bool> IsStudentVisible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvanceRequests> AdvanceRequests { get; set; }
    }
}
