//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetLocationsWithLevelsSelect_Vw
    {
        public int ID { get; set; }
        public string LocationName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<bool> IsShown { get; set; }
        public Nullable<bool> IsMain { get; set; }
        public Nullable<int> Com_ID { get; set; }
        public Nullable<bool> IsResidential { get; set; }
        public Nullable<int> MaxCount { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Depth { get; set; }
        public bool IsFamilial { get; set; }
        public string UnitNumber { get; set; }
        public Nullable<int> BedsPerRoom { get; set; }
        public int level { get; set; }
    }
}
