//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAttachments
    {
        public int ID { get; set; }
        public int SarafDownloaded_ID { get; set; }
        public string LineAsUploaded { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public int User_Id { get; set; }
        public Nullable<int> BankCode_Id { get; set; }
    
        public virtual BankCodes BankCodes { get; set; }
        public virtual SarafDownloaded SarafDownloaded { get; set; }
    }
}
