//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BCD()
        {
            this.CashMovement = new HashSet<CashMovement>();
            this.GJH = new HashSet<GJH>();
        }
    
        public int BCDID { get; set; }
        public string BCDArValue { get; set; }
        public string BCDEnValue { get; set; }
        public Nullable<bool> BCDStatus { get; set; }
        public Nullable<bool> BCDIsSystem { get; set; }
        public Nullable<int> BCDOrder { get; set; }
        public string BCDExp1 { get; set; }
        public string BCDExp2 { get; set; }
        public string BCDExp3 { get; set; }
        public Nullable<int> BSC_ID { get; set; }
        public string Prefix { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashMovement> CashMovement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GJH> GJH { get; set; }
    }
}
