//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        public int ID { get; set; }
        public string Bus_Number { get; set; }
        public string Bus_Driver { get; set; }
        public string Bus_DriverMobile { get; set; }
        public string SupervisorName { get; set; }
        public string SupervisorMobile { get; set; }
        public Nullable<int> COA_ID { get; set; }
        public Nullable<int> School_ID { get; set; }
    }
}
