//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashMovement
    {
        public int CashMovementId { get; set; }
        public int TreasuryId { get; set; }
        public long GJHID { get; set; }
        public Nullable<int> DocId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime MovementDate { get; set; }
        public int BCD_ID { get; set; }
        public Nullable<System.DateTime> PatchDate { get; set; }
        public string BeneficiaryName { get; set; }
        public string Notes { get; set; }
    
        public virtual BCD BCD { get; set; }
        public virtual DaftersDocuments DaftersDocuments { get; set; }
        public virtual GJH GJH { get; set; }
        public virtual Treasuries Treasuries { get; set; }
    }
}
