//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT()
        {
            this.AstNames = new HashSet<AstNames>();
        }
    
        public int CAT_ID { get; set; }
        public string CAT_Name { get; set; }
        public int COA_ID { get; set; }
        public int MainDepAcc { get; set; }
        public int MainTotalDepAcc { get; set; }
        public Nullable<int> DEP_ID { get; set; }
        public Nullable<decimal> DEP_Percent { get; set; }
        public Nullable<int> DepYears { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AstNames> AstNames { get; set; }
        public virtual COA COA { get; set; }
        public virtual COA COA1 { get; set; }
        public virtual COA COA2 { get; set; }
    }
}
