//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Checks()
        {
            this.ExchangeOrdersChecks = new HashSet<ExchangeOrdersChecks>();
        }
    
        public int ID { get; set; }
        public string CheckNumber { get; set; }
        public decimal CheckValue { get; set; }
        public System.DateTime InsertDate { get; set; }
        public System.DateTime IssueDate { get; set; }
        public int InsertedBy { get; set; }
        public Nullable<int> DeliveredTo { get; set; }
        public Nullable<int> DeliveredBy { get; set; }
        public Nullable<System.DateTime> DeliverDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExchangeOrdersChecks> ExchangeOrdersChecks { get; set; }
        public virtual DashBoard_Users DeliveredBy_User { get; set; }
        public virtual DashBoard_Users DeliverdTo_User { get; set; }
        public virtual DashBoard_Users InsertedBy_Users { get; set; }
    }
}
