//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoaTree_Vw
    {
        public int COAID { get; set; }
        public Nullable<int> COA_ID { get; set; }
        public string COACode { get; set; }
        public string COADescription { get; set; }
        public string AccountNatureName { get; set; }
        public string AccountTypeName { get; set; }
        public Nullable<int> COAAccountType { get; set; }
        public string COANotes { get; set; }
        public string COA_Type { get; set; }
        public string COMName { get; set; }
        public Nullable<int> COMID { get; set; }
    }
}
