//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COM()
        {
            this.Ast_Location = new HashSet<Ast_Location>();
            this.COA = new HashSet<COA>();
            this.Con_Company = new HashSet<Con_Company>();
            this.Dafters = new HashSet<Dafters>();
            this.FSY = new HashSet<FSY>();
            this.GJD = new HashSet<GJD>();
            this.GJH = new HashSet<GJH>();
            this.Treasuries = new HashSet<Treasuries>();
            this.Users = new HashSet<Users>();
        }
    
        public int COMID { get; set; }
        public string COMName { get; set; }
        public string COMDescription { get; set; }
        public string COMAddress { get; set; }
        public string COMUrl { get; set; }
        public byte[] COMLogo { get; set; }
        public string COMPhone { get; set; }
        public string COMFax { get; set; }
        public bool COMStatus { get; set; }
        public string DocFooter { get; set; }
        public Nullable<int> COM_ID { get; set; }
        public string Accountant_Name { get; set; }
        public string FM_Name { get; set; }
        public string GM_Name { get; set; }
        public Nullable<bool> Is_Multiple_owner { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> Current_AccountID { get; set; }
        public int CompanyId { get; set; }
        public string ComNameEn { get; set; }
        public string ComMobile { get; set; }
        public string ComEmail { get; set; }
        public Nullable<int> RevenueAccountID { get; set; }
        public string TaxNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ast_Location> Ast_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COA> COA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Con_Company> Con_Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dafters> Dafters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FSY> FSY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GJD> GJD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GJH> GJH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Treasuries> Treasuries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
    }
}
