//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class config
    {
        public int ID { get; set; }
        public string title { get; set; }
        public string Kay { get; set; }
        public string Value { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<decimal> Visa_Commision_Rate { get; set; }
        public Nullable<int> University_Code { get; set; }
    }
}
