//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryPopulation
    {
        public int CountryCode { get; set; }
        public string CountryArName { get; set; }
        public Nullable<decimal> Population { get; set; }
        public Nullable<decimal> MusliumPopulation { get; set; }
        public Nullable<decimal> MusliumRatio { get; set; }
    }
}
