//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dafters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dafters()
        {
            this.DaftersDocuments = new HashSet<DaftersDocuments>();
        }
    
        public int DafterId { get; set; }
        public int DafterNo { get; set; }
        public int DafterTypeId { get; set; }
        public int BranchId { get; set; }
        public int StartFrom { get; set; }
        public int EndTo { get; set; }
        public int FsyId { get; set; }
    
        public virtual COM COM { get; set; }
        public virtual Dafters Dafters1 { get; set; }
        public virtual Dafters Dafters2 { get; set; }
        public virtual DafterType DafterType { get; set; }
        public virtual FSY FSY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaftersDocuments> DaftersDocuments { get; set; }
    }
}
