//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashBoard_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DashBoard_Users()
        {
            this.ActivityApprovedPhases = new HashSet<ActivityApprovedPhases>();
            this.ActivityConfig = new HashSet<ActivityConfig>();
            this.ActivityRequestDetails = new HashSet<ActivityRequestDetails>();
            this.ActivityRequestMaster = new HashSet<ActivityRequestMaster>();
            this.ActivityRequestMaster1 = new HashSet<ActivityRequestMaster>();
            this.ActivityRequestMasterAttachments = new HashSet<ActivityRequestMasterAttachments>();
            this.ActivityRequestsArchive = new HashSet<ActivityRequestsArchive>();
            this.ActivityUsers = new HashSet<ActivityUsers>();
            this.AdvanceApprovedPhases = new HashSet<AdvanceApprovedPhases>();
            this.AdvancePaymentMaster = new HashSet<AdvancePaymentMaster>();
            this.AdvanceReceiveMaster = new HashSet<AdvanceReceiveMaster>();
            this.AdvanceRequests = new HashSet<AdvanceRequests>();
            this.AdvanceUsers = new HashSet<AdvanceUsers>();
            this.DeliverdBy_Checks = new HashSet<Checks>();
            this.DeliveredTo_Checks = new HashSet<Checks>();
            this.InsertedBy_Checks = new HashSet<Checks>();
            this.Dashboard_FilterGroupUsers = new HashSet<Dashboard_FilterGroupUsers>();
            this.Dashboard_SecretPermissions = new HashSet<Dashboard_SecretPermissions>();
            this.DashBoard_UserGroups = new HashSet<DashBoard_UserGroups>();
            this.IssuessCategoriesPermissions = new HashSet<IssuessCategoriesPermissions>();
            this.HousingSupervisorsRooms = new HashSet<HousingSupervisorsRooms>();
            this.HousingFurnitureCategories = new HashSet<HousingFurnitureCategories>();
            this.HousingFurnitureCategories1 = new HashSet<HousingFurnitureCategories>();
            this.HousingOfSudents = new HashSet<HousingOfSudents>();
            this.HousingOfSudents1 = new HashSet<HousingOfSudents>();
            this.HousingSupervisors = new HashSet<HousingSupervisors>();
            this.HousingSupervisors1 = new HashSet<HousingSupervisors>();
            this.PayrollPhasesUsers = new HashSet<PayrollPhasesUsers>();
            this.PhasesUsers = new HashSet<PhasesUsers>();
            this.StudentDocuments = new HashSet<StudentDocuments>();
            this.StudentDocumentsLog = new HashSet<StudentDocumentsLog>();
            this.TravelAdvertisement = new HashSet<TravelAdvertisement>();
            this.ViolationOfStudents = new HashSet<ViolationOfStudents>();
            this.ViolationForwords = new HashSet<ViolationForwords>();
            this.ViolationForwords1 = new HashSet<ViolationForwords>();
            this.ViolationOfStudents1 = new HashSet<ViolationOfStudents>();
            this.ViolationsDecisions = new HashSet<ViolationsDecisions>();
            this.ViolationsDecisions1 = new HashSet<ViolationsDecisions>();
            this.PayrollChecks = new HashSet<PayrollChecks>();
            this.StudentPayroll = new HashSet<StudentPayroll>();
            this.AcademicCommitteeUsers = new HashSet<AcademicCommitteeUsers>();
            this.AcademicCommitteeUsersPerm = new HashSet<AcademicCommitteeUsersPerm>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<System.DateTime> LastChangeDatetime { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string unencryptedUsername { get; set; }
        public Nullable<int> AccID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityApprovedPhases> ActivityApprovedPhases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityConfig> ActivityConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityRequestDetails> ActivityRequestDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityRequestMaster> ActivityRequestMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityRequestMaster> ActivityRequestMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityRequestMasterAttachments> ActivityRequestMasterAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityRequestsArchive> ActivityRequestsArchive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityUsers> ActivityUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvanceApprovedPhases> AdvanceApprovedPhases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvancePaymentMaster> AdvancePaymentMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvanceReceiveMaster> AdvanceReceiveMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvanceRequests> AdvanceRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvanceUsers> AdvanceUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checks> DeliverdBy_Checks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checks> DeliveredTo_Checks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checks> InsertedBy_Checks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dashboard_FilterGroupUsers> Dashboard_FilterGroupUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dashboard_SecretPermissions> Dashboard_SecretPermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashBoard_UserGroups> DashBoard_UserGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssuessCategoriesPermissions> IssuessCategoriesPermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HousingSupervisorsRooms> HousingSupervisorsRooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HousingFurnitureCategories> HousingFurnitureCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HousingFurnitureCategories> HousingFurnitureCategories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HousingOfSudents> HousingOfSudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HousingOfSudents> HousingOfSudents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HousingSupervisors> HousingSupervisors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HousingSupervisors> HousingSupervisors1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollPhasesUsers> PayrollPhasesUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhasesUsers> PhasesUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentDocuments> StudentDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentDocumentsLog> StudentDocumentsLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelAdvertisement> TravelAdvertisement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViolationOfStudents> ViolationOfStudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViolationForwords> ViolationForwords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViolationForwords> ViolationForwords1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViolationOfStudents> ViolationOfStudents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViolationsDecisions> ViolationsDecisions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViolationsDecisions> ViolationsDecisions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollChecks> PayrollChecks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentPayroll> StudentPayroll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcademicCommitteeUsers> AcademicCommitteeUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcademicCommitteeUsersPerm> AcademicCommitteeUsersPerm { get; set; }
    }
}
