//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpCourses
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string CourseName { get; set; }
        public string CoursePlace { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> CourseDays { get; set; }
        public string Degree { get; set; }
        public string CourseImagePath { get; set; }
        public Nullable<int> CourseTypes_ID { get; set; }
        public Nullable<int> DegreePercentage { get; set; }
    
        public virtual CourseTypes CourseTypes { get; set; }
    }
}
