//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpDocument
    {
        public int ID { get; set; }
        public int EmpID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public string IdentityNum { get; set; }
        public string DocImagePath { get; set; }
        public string BarCode { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
