//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.Relatives = new HashSet<Relatives>();
        }
    
        public int ID { get; set; }
        public string empFileNum { get; set; }
        public string Name { get; set; }
        public string EnName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public Nullable<int> NationaltyID { get; set; }
        public Nullable<short> Gender { get; set; }
        public string IDNumber { get; set; }
        public string CurrentAddress { get; set; }
        public Nullable<int> JobID { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Mobile2 { get; set; }
        public string Phone { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> JobLevelID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> MaritalStatusID { get; set; }
        public Nullable<int> ContractTypesID { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public Nullable<int> ContractTypeID { get; set; }
        public string Image { get; set; }
        public Nullable<int> HousingTypeID { get; set; }
        public Nullable<System.TimeSpan> AttendanceTime { get; set; }
        public Nullable<System.TimeSpan> LeavingTime { get; set; }
        public Nullable<int> UniverstyID { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> CashType { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string CareerInID { get; set; }
        public Nullable<int> SponsorID { get; set; }
        public Nullable<System.DateTime> ComingDate { get; set; }
        public string WorkOfficeNumber { get; set; }
        public Nullable<bool> OnTheJob { get; set; }
        public Nullable<bool> IsStoped { get; set; }
        public Nullable<int> LevelsDegreesID { get; set; }
        public string FingerprintID { get; set; }
        public string MachineID { get; set; }
        public Nullable<System.DateTime> EmploymentDate { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> StopedMonth { get; set; }
        public Nullable<int> Coa_ID { get; set; }
        public string AccountOwnerName { get; set; }
        public Nullable<int> SpecializationID { get; set; }
        public Nullable<int> FamilyNumbers { get; set; }
        public Nullable<int> FirstWorkPlace { get; set; }
        public string Notes { get; set; }
        public string HomeAddress { get; set; }
        public string HomePhone { get; set; }
        public string HomeMobile { get; set; }
        public string EditingNotes { get; set; }
        public string EmpType { get; set; }
        public Nullable<bool> IsExcluded { get; set; }
        public Nullable<System.DateTime> PlacementDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relatives> Relatives { get; set; }
    }
}
