//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESOL_ACADEMIC_RECORDS
    {
        public decimal student_id { get; set; }
        public string national_id { get; set; }
        public Nullable<decimal> major_no { get; set; }
        public string major_name { get; set; }
        public Nullable<decimal> study_code { get; set; }
        public string study_desc { get; set; }
        public decimal semester { get; set; }
        public Nullable<decimal> semester_gpa { get; set; }
        public Nullable<decimal> cum_gpa { get; set; }
    }
}
