//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeOrdersChecks
    {
        public int ID { get; set; }
        public int ExchangeOrderID { get; set; }
        public int CheckID { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public decimal Value { get; set; }
    
        public virtual Checks Checks { get; set; }
        public virtual ExchangeOrder ExchangeOrder { get; set; }
    }
}
