//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FSY()
        {
            this.Dafters = new HashSet<Dafters>();
            this.GJD = new HashSet<GJD>();
        }
    
        public int FSYID { get; set; }
        public System.DateTime FSYStartDate { get; set; }
        public System.DateTime FSYEndDate { get; set; }
        public bool FSYStatus { get; set; }
        public int COM_ID { get; set; }
        public Nullable<bool> Is_Open { get; set; }
        public string Fsy_Name { get; set; }
        public string FsyPrefix { get; set; }
        public Nullable<long> GJHID { get; set; }
    
        public virtual COM COM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dafters> Dafters { get; set; }
        public virtual GJH GJH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GJD> GJD { get; set; }
    }
}
