//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GJD
    {
        public long GJDID { get; set; }
        public long GJH_ID { get; set; }
        public decimal GJDDebitAmount { get; set; }
        public decimal GJDCreditAmount { get; set; }
        public int COA_ID { get; set; }
        public string GJDDescrition { get; set; }
        public Nullable<int> JOB_ID { get; set; }
        public Nullable<bool> GJDStatus { get; set; }
        public Nullable<int> Fsy_ID { get; set; }
        public Nullable<int> Com_ID { get; set; }
        public string Notes { get; set; }
    
        public virtual COA COA { get; set; }
        public virtual COM COM { get; set; }
        public virtual FSY FSY { get; set; }
        public virtual GJH GJH { get; set; }
        public virtual JOB JOB { get; set; }
    }
}
