//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupPermission
    {
        public long ID { get; set; }
        public int Group_ID { get; set; }
        public int Page_ID { get; set; }
        public Nullable<bool> Display { get; set; }
        public Nullable<bool> InsertA { get; set; }
        public Nullable<bool> UpdateA { get; set; }
        public Nullable<bool> DeleteA { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Groups Groups { get; set; }
    }
}
