//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HousingFurnituresOfStudent
    {
        public int Id { get; set; }
        public int HousingOfSudentId { get; set; }
        public int HousingFurnitureId { get; set; }
        public int Number { get; set; }
        public string Notes { get; set; }
        public System.DateTime ReceivingDate { get; set; }
        public string ReceivingNotes { get; set; }
        public int SupervisorIdWhoGive { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string ReturnNotes { get; set; }
        public Nullable<int> SupervisorIdWhoTake { get; set; }
        public int InsertedBy { get; set; }
        public System.DateTime InsertionDate { get; set; }
        public Nullable<int> LastEdittedBy { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
    
        public virtual HousingFurnitures HousingFurnitures { get; set; }
        public virtual HousingOfSudents HousingOfSudents { get; set; }
    }
}
