//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HousingOfSudents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HousingOfSudents()
        {
            this.HousingFurnituresOfStudent = new HashSet<HousingFurnituresOfStudent>();
        }
    
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int LocationId { get; set; }
        public System.DateTime HousingDate { get; set; }
        public int SupervisorIdWhoMakeHousing { get; set; }
        public string NotesOfHosing { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public Nullable<int> SupervisorIdWhoMakeLeave { get; set; }
        public string NotesOfLeave { get; set; }
        public int userId { get; set; }
        public System.DateTime InsertionDate { get; set; }
        public Nullable<int> LastEdittededBy { get; set; }
        public Nullable<System.DateTime> LastEdittedDate { get; set; }
        public int Opt_Id { get; set; }
        public Nullable<int> HousingRepacement_Id { get; set; }
        public int Opt_No { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HousingFurnituresOfStudent> HousingFurnituresOfStudent { get; set; }
        public virtual HousingLocationFurniture HousingLocationFurniture { get; set; }
        public virtual OperationTypes OperationTypes { get; set; }
        public virtual DashBoard_Users DashBoard_Users { get; set; }
        public virtual DashBoard_Users DashBoard_Users1 { get; set; }
    }
}
