//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HousingLocationFurniture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HousingLocationFurniture()
        {
            this.HousingOfSudents = new HashSet<HousingOfSudents>();
        }
    
        public int Id { get; set; }
        public int LocationId { get; set; }
        public Nullable<int> FurnitureId { get; set; }
        public string Barcode { get; set; }
        public int userId { get; set; }
        public System.DateTime InsertionDate { get; set; }
        public Nullable<bool> IsUsed { get; set; }
    
        public virtual HousingFurnitures HousingFurnitures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HousingOfSudents> HousingOfSudents { get; set; }
    }
}
