//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HousingSupervisorsRooms
    {
        public int Id { get; set; }
        public int SupervisorId { get; set; }
        public int LocationId { get; set; }
        public System.DateTime BackUpDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
    
        public virtual DashBoard_Users DashBoard_Users { get; set; }
    }
}
