//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTEGRATION_All_Graduate_Students
    {
        public int ID { get; set; }
        public Nullable<decimal> STUDENT_ID { get; set; }
        public Nullable<int> DEGREE_CODE { get; set; }
        public string DEGREE_DESC { get; set; }
        public Nullable<int> FACULTY_NO { get; set; }
        public string FACULTY_NAME { get; set; }
        public Nullable<int> MAJOR_NO { get; set; }
        public string MAJOR_NAME { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public string GRADUATION_SEMESTER { get; set; }
        public string DEC_NO { get; set; }
        public Nullable<System.DateTime> GRADUATE_DATE { get; set; }
        public string THESIS_LABEL { get; set; }
        public string THESIS_LABEL_S { get; set; }
        public Nullable<System.DateTime> DELIVERY_DATE { get; set; }
        public Nullable<System.DateTime> FORMATION_DATE { get; set; }
        public Nullable<System.DateTime> DEAN_MEETING_DATE { get; set; }
        public Nullable<System.DateTime> PRESENTATION_DATE { get; set; }
        public Nullable<int> TOTAL_WARNINGS { get; set; }
        public string SUPERVISOR_NAME { get; set; }
        public Nullable<int> TOTAL_OFFICIAL_SEMESTER { get; set; }
        public string STUDY_CODE { get; set; }
        public string STUDY_DESC { get; set; }
        public Nullable<int> STATUS_CODE { get; set; }
        public string STATUS_DESC { get; set; }
        public string JOIN_SEMESTER { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    }
}
