//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTEGRATION_All_STUDENTS_GRADUATES_WARNING
    {
        public int ID { get; set; }
        public Nullable<decimal> STUDENT_ID { get; set; }
        public string REASON { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    }
}
