//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssuesCategories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IssuesCategories()
        {
            this.Issues = new HashSet<Issues>();
            this.IssuessCategoriesPermissions = new HashSet<IssuessCategoriesPermissions>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int InsertedBy { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public Nullable<int> LastEdittedBy { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issues> Issues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssuessCategoriesPermissions> IssuessCategoriesPermissions { get; set; }
    }
}
