//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JOB()
        {
            this.GJD = new HashSet<GJD>();
        }
    
        public int JOBID { get; set; }
        public string JOBDescription { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public Nullable<int> Level { get; set; }
        public string JOBCode { get; set; }
        public Nullable<bool> JOBIsMain { get; set; }
        public Nullable<int> ComID { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GJD> GJD { get; set; }
    }
}
