//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessagesLog
    {
        public long MessageId { get; set; }
        public Nullable<int> StDetailID { get; set; }
        public decimal Student_Id { get; set; }
        public string Student_Name { get; set; }
        public string Student_Mobile { get; set; }
        public string National_Id { get; set; }
        public string MessageText { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
    }
}
