//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payroll()
        {
            this.AdvanceReceiveMaster = new HashSet<AdvanceReceiveMaster>();
            this.PayrollApproval = new HashSet<PayrollApproval>();
            this.StudentPayroll = new HashSet<StudentPayroll>();
            this.PayrollChecks = new HashSet<PayrollChecks>();
        }
    
        public int ID { get; set; }
        public int PayrollNumber { get; set; }
        public decimal TotalAmount { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<int> ExchangeOrderID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public string PayNo { get; set; }
        public string DafPayNo { get; set; }
        public Nullable<bool> IsMonetary { get; set; }
        public Nullable<bool> IsExportedCheck { get; set; }
        public string DafPayNo2 { get; set; }
        public Nullable<bool> IsMinister { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvanceReceiveMaster> AdvanceReceiveMaster { get; set; }
        public virtual ExchangeOrder ExchangeOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollApproval> PayrollApproval { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentPayroll> StudentPayroll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollChecks> PayrollChecks { get; set; }
    }
}
