//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollPhasesUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PayrollPhasesUsers()
        {
            this.PayrollApproval = new HashSet<PayrollApproval>();
        }
    
        public int ID { get; set; }
        public int PayrollPhaseID { get; set; }
        public int UserID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollApproval> PayrollApproval { get; set; }
        public virtual PayrollPhases PayrollPhases { get; set; }
        public virtual DashBoard_Users DashBoard_Users { get; set; }
    }
}
