//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollApproval
    {
        public int ID { get; set; }
        public int PayrollID { get; set; }
        public int PayrollPhaseUserID { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsRefused { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
    
        public virtual Payroll Payroll { get; set; }
        public virtual PayrollPhasesUsers PayrollPhasesUsers { get; set; }
    }
}
