//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhasesUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhasesUsers()
        {
            this.TravelOrderDetails = new HashSet<TravelOrderDetails>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public int PhaseID { get; set; }
        public string Signature { get; set; }
        public string Stamp1 { get; set; }
        public string Stamp2 { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual TravelOrderPhase TravelOrderPhase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelOrderDetails> TravelOrderDetails { get; set; }
        public virtual DashBoard_Users DashBoard_Users { get; set; }
    }
}
