//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relatives
    {
        public int ID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string Name { get; set; }
        public string Relationship { get; set; }
        public string IDNumber { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> PassExpDate { get; set; }
        public string PassImage { get; set; }
        public Nullable<System.DateTime> AccomadationExpiryDate { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<bool> HasInsurance { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
