//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RewardCategory()
        {
            this.RewardNationaltity = new HashSet<RewardNationaltity>();
            this.RewardMaster = new HashSet<RewardMaster>();
        }
    
        public int ID { get; set; }
        public string CategoryName_Arb { get; set; }
        public string CategoryName_Eng { get; set; }
        public string Cat_Name_Integration { get; set; }
        public int Cat_Code_Integration { get; set; }
        public Nullable<bool> IsSaudiTreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RewardNationaltity> RewardNationaltity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RewardMaster> RewardMaster { get; set; }
    }
}
