//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardDetails
    {
        public int ID { get; set; }
        public Nullable<int> RewardMaster_id { get; set; }
        public Nullable<int> Allowance_ID { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> AmountType_ID { get; set; }
        public Nullable<int> EducationType { get; set; }
        public decimal FromRate { get; set; }
        public decimal ToRate { get; set; }
        public Nullable<int> ClassesNo { get; set; }
        public Nullable<int> DuesNo { get; set; }
        public Nullable<bool> DependOnEducationDays { get; set; }
        public Nullable<bool> DependOnEducationPeriod { get; set; }
        public Nullable<decimal> MiniHoursNo { get; set; }
        public Nullable<int> RateType { get; set; }
        public int RegisterTypeId { get; set; }
    
        public virtual RewardItems RewardItems { get; set; }
        public virtual RewardMaster RewardMaster { get; set; }
    }
}
