//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RewardItems()
        {
            this.PayrollRefusal = new HashSet<PayrollRefusal>();
            this.RewardDetails = new HashSet<RewardDetails>();
            this.StudentPayroll = new HashSet<StudentPayroll>();
        }
    
        public int ID { get; set; }
        public string RewardItemName_Arb { get; set; }
        public string RewardItemName_Eng { get; set; }
        public Nullable<int> RewardItemType_Id { get; set; }
        public Nullable<int> RewardItemExpensesType_Id { get; set; }
        public Nullable<bool> AfterCheckingResult { get; set; }
        public Nullable<bool> IsAdvanceReturn { get; set; }
        public Nullable<int> COAID { get; set; }
        public Nullable<int> CoaId_RecieveFromPayroll { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollRefusal> PayrollRefusal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RewardDetails> RewardDetails { get; set; }
        public virtual RewardItemExpensesTypes RewardItemExpensesTypes { get; set; }
        public virtual RewardItemTypes RewardItemTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentPayroll> StudentPayroll { get; set; }
    }
}
