//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunawayAliens
    {
        public long RunwayAlienId { get; set; }
        public string IdNumber { get; set; }
        public string student_name { get; set; }
        public string nationality { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> IssuanceDate { get; set; }
        public Nullable<bool> InKsa { get; set; }
    }
}
