//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SarafDownloaded
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SarafDownloaded()
        {
            this.BankAttachments = new HashSet<BankAttachments>();
        }
    
        public int Id { get; set; }
        public string StudentId { get; set; }
        public string AccountNumber { get; set; }
        public string StudentName { get; set; }
        public string NationalId { get; set; }
        public decimal NetValue { get; set; }
        public System.DateTime TomorowDate { get; set; }
        public string MobileNumber { get; set; }
        public decimal BasicSalary { get; set; }
        public decimal AllowanceHouse { get; set; }
        public decimal OtherAllowence { get; set; }
        public decimal deductions { get; set; }
        public int PayrollNumber { get; set; }
        public string LineAsDownloaded { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankAttachments> BankAttachments { get; set; }
    }
}
