//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScMessages
    {
        public int ID { get; set; }
        public string MsgTitle { get; set; }
        public string MessageText { get; set; }
        public int School_ID { get; set; }
    }
}
