//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_AcademicData
    {
        public long ID { get; set; }
        public Nullable<long> STUDENT_ID { get; set; }
        public string NATIONAL_ID { get; set; }
        public Nullable<int> MAJOR_NO { get; set; }
        public string MAJOR_NAME { get; set; }
        public Nullable<int> STUDY_CODE { get; set; }
        public string STUDY_DESC { get; set; }
        public Nullable<int> SEMESTER { get; set; }
        public Nullable<double> SEMESTER_GPA { get; set; }
        public Nullable<double> CUM_GPA { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    }
}
