//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StDetails
    {
        public int ID { get; set; }
        public int StDetailID { get; set; }
        public int RowLevel_ID { get; set; }
        public int Year_ID { get; set; }
        public Nullable<int> Class_ID { get; set; }
        public Nullable<decimal> PrevBalance { get; set; }
        public Nullable<int> Bus_ID { get; set; }
        public Nullable<int> Semester_ID { get; set; }
        public Nullable<int> BusType { get; set; }
        public string OrderType { get; set; }
        public Nullable<int> StudentStatus { get; set; }
        public Nullable<int> tempr { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
        public Nullable<System.DateTime> LastMessageDate { get; set; }
    
        public virtual RowLevel RowLevel { get; set; }
        public virtual StudentBasicData StudentBasicData { get; set; }
    }
}
