//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFiles
    {
        public int FileId { get; set; }
        public int StudentNoteId { get; set; }
        public string FilePath { get; set; }
    
        public virtual StudentNotes StudentNotes { get; set; }
    }
}
