//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentNotes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentNotes()
        {
            this.StudentFiles = new HashSet<StudentFiles>();
        }
    
        public int NoteId { get; set; }
        public int StDetailId { get; set; }
        public string NoteDetails { get; set; }
        public Nullable<bool> IsSecret { get; set; }
        public Nullable<bool> IsTopSecret { get; set; }
        public Nullable<int> IssueId { get; set; }
        public Nullable<System.DateTime> NoteDate { get; set; }
        public Nullable<byte> Evaluation { get; set; }
        public int AddedBy { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public string Punishment { get; set; }
        public Nullable<int> PunichedBy { get; set; }
    
        public virtual Issues Issues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentFiles> StudentFiles { get; set; }
    }
}
