//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsCustomFields
    {
        public int StudentCustomFieldId { get; set; }
        public string StudentId { get; set; }
        public string NationalId { get; set; }
        public int CustomFieldId { get; set; }
        public string Note { get; set; }
    
        public virtual CustomFields CustomFields { get; set; }
    }
}
