//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPayroll
    {
        public int ID { get; set; }
        public int PayrollID { get; set; }
        public int StudentID { get; set; }
        public int Item_ID { get; set; }
        public decimal Value { get; set; }
        public int StudentStatus_ID { get; set; }
        public System.DateTime RegisterationDate { get; set; }
        public System.DateTime SemesterStartDate { get; set; }
        public System.DateTime SemesterEndDate { get; set; }
        public int NoOfDays { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public string DelevirFileName { get; set; }
        public string DelevirFilePath { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> BeneficiaryID { get; set; }
        public Nullable<bool> IsPosted { get; set; }
    
        public virtual Payroll Payroll { get; set; }
        public virtual RewardItems RewardItems { get; set; }
        public virtual DashBoard_Users DashBoard_Users { get; set; }
    }
}
