//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsTicketsDetails
    {
        public int ID { get; set; }
        public int StudentsTravelOrderID { get; set; }
        public string FromCity { get; set; }
        public string ToCity { get; set; }
        public string TicketNumber { get; set; }
        public decimal TicketValue { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
    
        public virtual StudentsTravelOrder StudentsTravelOrder { get; set; }
    }
}
