//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsTravelOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentsTravelOrder()
        {
            this.StudentsTicketsDetails = new HashSet<StudentsTicketsDetails>();
        }
    
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int TravelOrderID { get; set; }
        public Nullable<decimal> GivenAmount { get; set; }
        public Nullable<decimal> ApprovedAmount { get; set; }
        public Nullable<int> StTravelRequestID { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string TicketNumber { get; set; }
    
        public virtual StTravelRequest StTravelRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsTicketsDetails> StudentsTicketsDetails { get; set; }
        public virtual TravelOrders TravelOrders { get; set; }
    }
}
