//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDocuments
    {
        public int StudentDocumentID { get; set; }
        public int Document_ID { get; set; }
        public int UniversityStudent_ID { get; set; }
        public string IdentityNumber { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string DocumentImage { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public bool IsNew { get; set; }
        public string RefusedNotes { get; set; }
        public Nullable<System.DateTime> RefusedDate { get; set; }
        public Nullable<bool> IsTransfer { get; set; }
        public Nullable<bool> IsExpired { get; set; }
        public Nullable<bool> FromMuqim { get; set; }
    
        public virtual UniversityStudents UniversityStudents { get; set; }
        public virtual DashBoard_Users DashBoard_Users { get; set; }
    }
}
