//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentBasicData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentBasicData()
        {
            this.StDetails = new HashSet<StDetails>();
        }
    
        public int ID { get; set; }
        public string FisrtName { get; set; }
        public int Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Region { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public int Staus_ID { get; set; }
        public string IDNumber { get; set; }
        public Nullable<System.DateTime> CatchDate { get; set; }
        public string LastSchool { get; set; }
        public string PlaceOfBirth { get; set; }
        public int Father_ID { get; set; }
        public int School_ID { get; set; }
        public Nullable<int> Bus_ID { get; set; }
        public string StImg { get; set; }
        public Nullable<bool> IsActice { get; set; }
        public Nullable<int> StudyType { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public string Name_En { get; set; }
        public Nullable<int> NationaltityID { get; set; }
        public Nullable<int> Department_ID { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<double> StudentCode { get; set; }
        public string AccountNO { get; set; }
        public string idst { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StDetails> StDetails { get; set; }
    }
}
