//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelOrderDetails
    {
        public int ID { get; set; }
        public int TravelOrderID { get; set; }
        public int PhaseUserID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual PhasesUsers PhasesUsers { get; set; }
        public virtual TravelOrders TravelOrders { get; set; }
    }
}
