//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelOrders()
        {
            this.StudentsTravelOrder = new HashSet<StudentsTravelOrder>();
            this.TravelOrderDetails = new HashSet<TravelOrderDetails>();
        }
    
        public int ID { get; set; }
        public string TripNumber { get; set; }
        public string TripPath { get; set; }
        public string AgentRefNumber { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public int CreatedBy { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
        public Nullable<int> CanceledBy { get; set; }
        public Nullable<int> TripType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsTravelOrder> StudentsTravelOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelOrderDetails> TravelOrderDetails { get; set; }
    }
}
