//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treasuries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Treasuries()
        {
            this.CashMovement = new HashSet<CashMovement>();
        }
    
        public int TreasuryId { get; set; }
        public int BranchId { get; set; }
        public string TreasuryName { get; set; }
        public int CashAccount { get; set; }
        public int CheckAccount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashMovement> CashMovement { get; set; }
        public virtual COA COA { get; set; }
        public virtual COA COA1 { get; set; }
        public virtual COM COM { get; set; }
    }
}
