//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversityStudents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UniversityStudents()
        {
            this.Emergency = new HashSet<Emergency>();
            this.StudentDocuments = new HashSet<StudentDocuments>();
            this.StudentDocumentsLog = new HashSet<StudentDocumentsLog>();
        }
    
        public int ID { get; set; }
        public int Student_ID { get; set; }
        public string National_ID { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<System.DateTime> LastPhoneVerificationDate { get; set; }
        public string UniversityEmail { get; set; }
        public string PersonalEmail { get; set; }
        public Nullable<System.DateTime> LastEmailVerificationDate { get; set; }
        public string NamePerPassport_Ar { get; set; }
        public string NamePerIdentity_Ar { get; set; }
        public string NamePerPassport_En { get; set; }
        public string NamePerIdentity_En { get; set; }
        public Nullable<int> Nationality_ID { get; set; }
        public Nullable<int> Country_ID { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> OriginalCountry { get; set; }
        public string OriginalCity { get; set; }
        public string ImageName { get; set; }
        public Nullable<bool> IsSaudi { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emergency> Emergency { get; set; }
        public virtual Nationality Nationality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentDocuments> StudentDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentDocumentsLog> StudentDocumentsLog { get; set; }
    }
}
