//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.AccountSecurity = new HashSet<AccountSecurity>();
            this.Con_Company = new HashSet<Con_Company>();
            this.GJH = new HashSet<GJH>();
        }
    
        public int ID { get; set; }
        public string Acc_Name { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public Nullable<int> School_ID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> EnableDocDate { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public bool EnableUserAccounts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountSecurity> AccountSecurity { get; set; }
        public virtual COM COM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Con_Company> Con_Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GJH> GJH { get; set; }
    }
}
