//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SIS_VIOLATION_SINGLE
    {
        public decimal VIOLATION_NO { get; set; }
        public Nullable<decimal> STUDENT_ID { get; set; }
        public Nullable<decimal> VIOLATION_CODE { get; set; }
        public Nullable<decimal> SEMESTER { get; set; }
        public string INCIDENT_DATE { get; set; }
        public System.DateTime VIOLATION_DESC { get; set; }
    }
}
