//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViolationForwords
    {
        public int Id { get; set; }
        public int ViolationId { get; set; }
        public int UserId { get; set; }
        public int InsertedBy { get; set; }
        public System.DateTime InsertedDate { get; set; }
    
        public virtual ViolationOfStudents ViolationOfStudents { get; set; }
        public virtual DashBoard_Users DashBoard_Users { get; set; }
        public virtual DashBoard_Users DashBoard_Users1 { get; set; }
    }
}
