//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Get_AdvanceSetting_DSource
    {
        public string AdvanceType { get; set; }
        public int AdvanceConfigId { get; set; }
        public string AdvanceName { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string ValueType { get; set; }
        public string COADescription { get; set; }
        public int COAID { get; set; }
        public Nullable<decimal> MaxRequestValue { get; set; }
    }
}
