//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GetAllRewardCategories
    {
        public int RewardCategoryId { get; set; }
        public string RewardCategoryName { get; set; }
        public string RewardCategoryNameEng { get; set; }
        public int Cat_Code_Integration { get; set; }
        public string Cat_Name_Integration { get; set; }
        public int NationalityID { get; set; }
        public string NationalityDesc { get; set; }
    }
}
