//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfile.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_UnitParents
    {
        public int SiteId { get; set; }
        public string SiteName { get; set; }
        public Nullable<int> MaxCount { get; set; }
        public int FloorId { get; set; }
        public string FloorName { get; set; }
        public int DepartmentId { get; set; }
        public Nullable<bool> IsResidential { get; set; }
        public bool IsFamilial { get; set; }
        public string DepartementName { get; set; }
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
    }
}
